name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  scan:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "runs-on/action@46910bf61b41721b0579f237e186afb35477007a" # v2
      - uses: "trufflesecurity/trufflehog@20652fbbdefffcdaa493a5bf57ab2ac6b1db715b" # main
        with:
          extra_args: "--results=verified,unknown"
