directive @goField(
  forceResolver: Boolean
  name: String
  omittable: Boolean
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @goModel(
  model: String
  models: [String!]
) on OBJECT | INPUT_OBJECT | SCALAR | ENUM | INTERFACE | UNION

directive @goEnum(value: String) on ENUM_VALUE

scalar BigInt
scalar CursorKey
scalar Datetime
scalar Upload
scalar EmailAddr
scalar OAuth2Scope
scalar Map

type Period {
  start: Datetime
  end: Datetime
}

input PeriodInput {
  start: Datetime @goField(omittable: true)
  end: Datetime @goField(omittable: true)
}

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node @authentication(required: PRESENT)
  viewer: Identity @authentication(required: PRESENT)
  ssoLoginURL(email: EmailAddr!): String
    @goField(forceResolver: true)
    @authentication(required: OPTIONAL)
  oidcProviders: [OIDCProviderInfo!]!
    @goField(forceResolver: true)
    @authentication(required: OPTIONAL)
  signUpEnabled: Boolean!
    @goField(forceResolver: true)
    @authentication(required: OPTIONAL)
  slackbotAvailable: Boolean!
    @goField(forceResolver: true)
    @authentication(required: PRESENT)
  oauth2ScopesSupported: [OAuth2Scope!]!
    @goField(forceResolver: true)
    @authentication(required: OPTIONAL)
  oauthClientBranding(clientId: String): OAuthClientBranding
    @goField(forceResolver: true)
    @authentication(required: OPTIONAL)
}

type OAuthClientBranding {
  name: String!
  logoUrl: String
  clientURL: String
}

type OIDCProviderInfo {
  name: String!
  loginURL: String!
}

type Mutation
