package complianceportal_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/complianceportal/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// UpdateFullName is the resolver for the updateFullName field.
func (r *mutationResolver) UpdateFullName(ctx context.Context, input types.UpdateFullNameInput) (*types.UpdateFullNamePayload, error) {
	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to request access")
	}

	if _, err := r.iam.AccountService.UpdateIdentity(
		ctx,
		identity.ID,
		&iam.UpdateIdentityRequest{
			FullName: input.FullName,
		},
	); err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update identity", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateFullNamePayload{Success: true}, nil
}

// UpdateLocale is the resolver for the updateLocale field.
func (r *mutationResolver) UpdateLocale(ctx context.Context, input types.UpdateLocaleInput) (*types.UpdateLocalePayload, error) {
	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to update locale")
	}

	identity, err := r.iam.AccountService.UpdateLocale(
		ctx,
		identity.ID,
		&iam.UpdateLocaleRequest{
			Locale: input.Locale,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update identity locale", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateLocalePayload{
		Identity: &types.Identity{
			ID:            identity.ID,
			Email:         identity.EmailAddress,
			FullName:      identity.FullName,
			EmailVerified: identity.EmailAddressVerified,
			Locale:        identity.Locale,
			CreatedAt:     identity.CreatedAt,
			UpdatedAt:     identity.UpdatedAt,
		},
	}, nil
}

// SignOut is the resolver for the signOut field.
func (r *mutationResolver) SignOut(ctx context.Context) (*types.SignOutPayload, error) {
	session := authn.SessionFromContext(ctx)

	err := r.iam.SessionService.CloseSession(ctx, session.ID)
	if err != nil {
		_, notFound := errors.AsType[*iam.ErrSessionNotFound](err)

		_, expired := errors.AsType[*iam.ErrSessionExpired](err)
		if !notFound && !expired {
			r.logger.ErrorCtx(ctx, "cannot close session", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		// Already closed or missing — still clear the cookie so the browser
		// drops the stale session on concurrent / retried logout.
	}

	w := gqlutils.HTTPResponseWriterFromContext(ctx)
	r.sessionCookie.Clear(w)

	return &types.SignOutPayload{Success: true}, nil
}
