package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// Organization is the resolver for the organization field.
func (r *aiSystemResolver) Organization(ctx context.Context, obj *types.AiSystem) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get ai system organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Owner is the resolver for the owner field.
func (r *aiSystemResolver) Owner(ctx context.Context, obj *types.AiSystem) (*types.Profile, error) {
	if obj.Owner == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.Owner.ID, iam.ActionMembershipProfileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	owner, err := loaders.Profile.Load(ctx, obj.Owner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get ai system owner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(owner), nil
}

// Permission is the resolver for the permission field.
func (r *aiSystemResolver) Permission(ctx context.Context, obj *types.AiSystem, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *aiSystemConnectionResolver) TotalCount(ctx context.Context, obj *types.AiSystemConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionAiSystemList)
	if err != nil {
		return 0, err
	}

	var (
		status             *coredata.AiSystemStatus
		riskClassification *coredata.AiSystemRiskClassification
	)

	if obj.Filter != nil {
		status = obj.Filter.Status
		riskClassification = obj.Filter.RiskClassification
	}

	filter := coredata.NewAiSystemFilter(status, riskClassification)

	count, err := r.probo.AiSystems.CountForOrganizationID(ctx, scope, obj.ParentID, filter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count ai systems", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CreateAiSystem is the resolver for the createAiSystem field.
func (r *mutationResolver) CreateAiSystem(ctx context.Context, input types.CreateAiSystemInput) (*types.CreateAiSystemPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionAiSystemCreate)
	if err != nil {
		return nil, err
	}

	riskClassification := input.RiskClassification

	req := probo.CreateAiSystemRequest{
		OrganizationID:          input.OrganizationID,
		Name:                    input.Name,
		Version:                 input.Version,
		CompanyRoles:            input.CompanyRoles,
		Status:                  input.Status,
		OwnerID:                 input.OwnerID,
		Source:                  input.Source,
		Purpose:                 input.Purpose,
		IntendedUseCases:        input.IntendedUseCases,
		AutonomyLevel:           input.AutonomyLevel,
		HumanOversightMechanism: input.HumanOversightMechanism,
		RiskClassification:      &riskClassification,
		KeyStakeholders:         input.KeyStakeholders,
		DataSourcesAndType:      input.DataSourcesAndType,
		DeploymentDate:          input.DeploymentDate,
		LastReviewDate:          input.LastReviewDate,
		NextReviewDate:          input.NextReviewDate,
		Notes:                   input.Notes,
	}

	aiSystem, err := r.probo.AiSystems.Create(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot create ai system", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateAiSystemPayload{
		AiSystemEdge: types.NewAiSystemEdge(aiSystem, coredata.AiSystemOrderFieldCreatedAt),
	}, nil
}

// UpdateAiSystem is the resolver for the updateAiSystem field.
func (r *mutationResolver) UpdateAiSystem(ctx context.Context, input types.UpdateAiSystemInput) (*types.UpdateAiSystemPayload, error) {
	scope, err := r.authorize(ctx, input.ID, probo.ActionAiSystemUpdate)
	if err != nil {
		return nil, err
	}

	req := probo.UpdateAiSystemRequest{
		ID:                      input.ID,
		Name:                    gqlutils.UnwrapOmittable(input.Name),
		Version:                 gqlutils.UnwrapOmittable(input.Version),
		Status:                  gqlutils.UnwrapOmittable(input.Status),
		CompanyRoles:            gqlutils.UnwrapOmittable(input.CompanyRoles),
		OwnerID:                 gqlutils.UnwrapOmittable(input.OwnerID),
		Source:                  gqlutils.UnwrapOmittable(input.Source),
		Purpose:                 gqlutils.UnwrapOmittable(input.Purpose),
		IntendedUseCases:        gqlutils.UnwrapOmittable(input.IntendedUseCases),
		AutonomyLevel:           gqlutils.UnwrapOmittable(input.AutonomyLevel),
		HumanOversightMechanism: gqlutils.UnwrapOmittable(input.HumanOversightMechanism),
		RiskClassification:      gqlutils.UnwrapOmittable(input.RiskClassification),
		KeyStakeholders:         gqlutils.UnwrapOmittable(input.KeyStakeholders),
		DataSourcesAndType:      gqlutils.UnwrapOmittable(input.DataSourcesAndType),
		DeploymentDate:          gqlutils.UnwrapOmittable(input.DeploymentDate),
		LastReviewDate:          gqlutils.UnwrapOmittable(input.LastReviewDate),
		NextReviewDate:          gqlutils.UnwrapOmittable(input.NextReviewDate),
		Notes:                   gqlutils.UnwrapOmittable(input.Notes),
	}

	aiSystem, err := r.probo.AiSystems.Update(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot update ai system", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateAiSystemPayload{
		AiSystem: types.NewAiSystem(aiSystem),
	}, nil
}

// DeleteAiSystem is the resolver for the deleteAiSystem field.
func (r *mutationResolver) DeleteAiSystem(ctx context.Context, input types.DeleteAiSystemInput) (*types.DeleteAiSystemPayload, error) {
	scope, err := r.authorize(ctx, input.AiSystemID, probo.ActionAiSystemDelete)
	if err != nil {
		return nil, err
	}

	if err := r.probo.AiSystems.Delete(ctx, scope, input.AiSystemID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete ai system", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteAiSystemPayload{
		DeletedAiSystemID: input.AiSystemID,
	}, nil
}

// PublishAiSystemList is the resolver for the publishAiSystemList field.
func (r *mutationResolver) PublishAiSystemList(ctx context.Context, input types.PublishAiSystemListInput) (*types.PublishAiSystemListPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionAiSystemPublish)
	if err != nil {
		return nil, err
	}

	document, documentVersion, err := r.probo.GeneratedDocuments.PublishAiSystemList(ctx, scope, input.OrganizationID, input.ApproverIds, input.Minor)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot publish ai system list", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.PublishAiSystemListPayload{
		DocumentEdge:        types.NewDocumentEdge(document, coredata.DocumentOrderFieldCreatedAt),
		DocumentVersionEdge: types.NewDocumentVersionEdge(documentVersion, coredata.DocumentVersionOrderFieldCreatedAt),
	}, nil
}

// AiSystem returns schema.AiSystemResolver implementation.
func (r *Resolver) AiSystem() schema.AiSystemResolver { return &aiSystemResolver{r} }

// AiSystemConnection returns schema.AiSystemConnectionResolver implementation.
func (r *Resolver) AiSystemConnection() schema.AiSystemConnectionResolver {
	return &aiSystemConnectionResolver{r}
}

type (
	aiSystemResolver           struct{ *Resolver }
	aiSystemConnectionResolver struct{ *Resolver }
)
