package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// TotalCount is the resolver for the totalCount field.
func (r *commonGVLVendorConnectionResolver) TotalCount(ctx context.Context, obj *types.CommonGVLVendorConnection) (int, error) {
	if obj.ParentID != nil {
		scope, err := r.authorize(ctx, *obj.ParentID, probo.ActionCookieBannerGet)
		if err != nil {
			return 0, err
		}

		count, err := r.cookieBanner.CountCookieBannerGVLVendors(ctx, scope, *obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count cookie banner gvl vendors", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	}

	identity := authn.IdentityFromContext(ctx)

	if _, err := r.authorize(ctx, identity.ID, probo.ActionCommonGVLVendorList); err != nil {
		return 0, err
	}

	count, err := r.cookieBanner.CountCommonGVLVendors(ctx, obj.Filter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count common gvl vendors", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CommonGVLVendorConnection returns schema.CommonGVLVendorConnectionResolver implementation.
func (r *Resolver) CommonGVLVendorConnection() schema.CommonGVLVendorConnectionResolver {
	return &commonGVLVendorConnectionResolver{r}
}

type commonGVLVendorConnectionResolver struct{ *Resolver }
