package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/probot/identitybinding"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// ConfirmProbotIdentityBinding is the resolver for the confirmProbotIdentityBinding field.
func (r *mutationResolver) ConfirmProbotIdentityBinding(ctx context.Context, input types.ConfirmProbotIdentityBindingInput) (*types.ConfirmProbotIdentityBindingPayload, error) {
	if r.probotIdentityBindings == nil {
		return nil, gqlutils.Internal(ctx)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Internal(ctx)
	}

	binding, err := r.probotIdentityBindings.Confirm(
		ctx,
		identity.ID,
		input.Token,
	)
	if err != nil {
		switch {
		case errors.Is(err, identitybinding.ErrAlreadyBound),
			errors.Is(err, identitybinding.ErrChallengeAlreadyUsed):
			return nil, gqlutils.Conflict(ctx, err)
		case errors.Is(err, identitybinding.ErrChallengeExpired),
			errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.Invalid(ctx, err)
		default:
			r.logger.ErrorCtx(
				ctx,
				"cannot confirm Probot identity binding",
				log.Error(err),
			)

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.ConfirmProbotIdentityBindingPayload{
		ProbotIdentityBinding: types.NewProbotIdentityBinding(binding),
		Viewer:                currentViewer(ctx),
	}, nil
}

// DeleteProbotIdentityBinding is the resolver for the deleteProbotIdentityBinding field.
func (r *mutationResolver) DeleteProbotIdentityBinding(ctx context.Context, input types.DeleteProbotIdentityBindingInput) (*types.DeleteProbotIdentityBindingPayload, error) {
	if r.probotIdentityBindings == nil {
		return nil, gqlutils.Internal(ctx)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Internal(ctx)
	}

	err := r.probotIdentityBindings.Delete(ctx, identity.ID, input.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(
			ctx,
			"cannot delete Probot identity binding",
			log.Error(err),
		)

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteProbotIdentityBindingPayload{
		ProbotIdentityBindingID: input.ID,
		Viewer:                  currentViewer(ctx),
	}, nil
}
