package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"time"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/riskmanagement"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// CreateRiskAnalysis is the resolver for the createRiskAnalysis field.
func (r *mutationResolver) CreateRiskAnalysis(ctx context.Context, input types.CreateRiskAnalysisInput) (*types.CreateRiskAnalysisPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, riskmanagement.ActionRiskAnalysisCreate)
	if err != nil {
		return nil, err
	}

	var period *riskmanagement.Period

	if input.Period != nil {
		start, end := types.PeriodInputDates(input.Period)
		period = &riskmanagement.Period{
			Start: start,
			End:   end,
		}
	}

	ra, err := r.riskManagement.Create(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisRequest{
			OrganizationID: input.OrganizationID,
			Name:           input.Name,
			Description:    input.Description,
			Period:         period,
			MatrixSize:     input.MatrixSize,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk assessment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisPayload{
		RiskAnalysisEdge: types.NewRiskAnalysisConnectionEdge(ra, coredata.RiskAnalysisOrderFieldCreatedAt),
	}, nil
}

// UpdateRiskAnalysis is the resolver for the updateRiskAnalysis field.
func (r *mutationResolver) UpdateRiskAnalysis(ctx context.Context, input types.UpdateRiskAnalysisInput) (*types.UpdateRiskAnalysisPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisUpdate)
	if err != nil {
		return nil, err
	}

	var period *riskmanagement.Period

	if input.Period != nil {
		start, end := types.PeriodInputDates(input.Period)
		period = &riskmanagement.Period{
			Start: start,
			End:   end,
		}
	}

	ra, err := r.riskManagement.Update(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisRequest{
			ID:          input.ID,
			Name:        input.Name,
			Description: gqlutils.UnwrapOmittable(input.Description),
			Period:      period,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk assessment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisPayload{RiskAnalysis: types.NewRiskAnalysis(ra)}, nil
}

// DeleteRiskAnalysis is the resolver for the deleteRiskAnalysis field.
func (r *mutationResolver) DeleteRiskAnalysis(ctx context.Context, input types.DeleteRiskAnalysisInput) (*types.DeleteRiskAnalysisPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisID, riskmanagement.ActionRiskAnalysisDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.Delete(ctx, scope, input.RiskAnalysisID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk assessment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisPayload{DeletedRiskAnalysisID: input.RiskAnalysisID}, nil
}

// ForkRiskAnalysis is the resolver for the forkRiskAnalysis field.
func (r *mutationResolver) ForkRiskAnalysis(ctx context.Context, input types.ForkRiskAnalysisInput) (*types.ForkRiskAnalysisPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisID, riskmanagement.ActionRiskAnalysisGet)
	if err != nil {
		if gqlutils.IsForbidden(err) {
			return nil, gqlutils.NotFoundf(ctx, "risk analysis not found")
		}

		return nil, err
	}

	source, err := r.riskManagement.Get(ctx, scope, input.RiskAnalysisID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot load risk analysis", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scope, err = r.authorize(ctx, source.OrganizationID, riskmanagement.ActionRiskAnalysisCreate)
	if err != nil {
		return nil, err
	}

	var period *riskmanagement.Period

	if input.Period != nil {
		start, end := types.PeriodInputDates(input.Period)
		period = &riskmanagement.Period{
			Start: start,
			End:   end,
		}
	}

	ra, err := r.riskManagement.Fork(
		ctx,
		scope,
		riskmanagement.ForkRiskAnalysisRequest{
			RiskAnalysisID: input.RiskAnalysisID,
			Name:           input.Name,
			Description:    input.Description,
			Period:         period,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot fork risk analysis", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.ForkRiskAnalysisPayload{
		RiskAnalysisEdge: types.NewRiskAnalysisConnectionEdge(ra, coredata.RiskAnalysisOrderFieldCreatedAt),
	}, nil
}

// CreateRiskAnalysisDiagram is the resolver for the createRiskAnalysisDiagram field.
func (r *mutationResolver) CreateRiskAnalysisDiagram(ctx context.Context, input types.CreateRiskAnalysisDiagramInput) (*types.CreateRiskAnalysisDiagramPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisID, riskmanagement.ActionRiskAnalysisDiagramCreate)
	if err != nil {
		return nil, err
	}

	raDiagram, err := r.riskManagement.CreateDiagram(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisDiagramRequest{
			RiskAnalysisID: input.RiskAnalysisID,
			Name:           input.Name,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk assessment scope", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisDiagramPayload{
		RiskAnalysisDiagramEdge: types.NewRiskAnalysisDiagramConnectionEdge(raDiagram, coredata.RiskAnalysisDiagramOrderFieldCreatedAt),
	}, nil
}

// UpdateRiskAnalysisDiagram is the resolver for the updateRiskAnalysisDiagram field.
func (r *mutationResolver) UpdateRiskAnalysisDiagram(ctx context.Context, input types.UpdateRiskAnalysisDiagramInput) (*types.UpdateRiskAnalysisDiagramPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisDiagramUpdate)
	if err != nil {
		return nil, err
	}

	raDiagram, err := r.riskManagement.UpdateDiagram(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisDiagramRequest{
			ID:   input.ID,
			Name: input.Name,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk assessment scope", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisDiagramPayload{RiskAnalysisDiagram: types.NewRiskAnalysisDiagram(raDiagram)}, nil
}

// DeleteRiskAnalysisDiagram is the resolver for the deleteRiskAnalysisDiagram field.
func (r *mutationResolver) DeleteRiskAnalysisDiagram(ctx context.Context, input types.DeleteRiskAnalysisDiagramInput) (*types.DeleteRiskAnalysisDiagramPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisDiagramDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteDiagram(ctx, scope, input.RiskAnalysisDiagramID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk assessment scope", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisDiagramPayload{DeletedRiskAnalysisDiagramID: input.RiskAnalysisDiagramID}, nil
}

// CreateRiskAnalysisNode is the resolver for the createRiskAnalysisNode field.
func (r *mutationResolver) CreateRiskAnalysisNode(ctx context.Context, input types.CreateRiskAnalysisNodeInput) (*types.CreateRiskAnalysisNodePayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisNodeCreate)
	if err != nil {
		return nil, err
	}

	node, err := r.riskManagement.CreateNode(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisNodeRequest{
			RiskAnalysisDiagramID: input.RiskAnalysisDiagramID,
			BoundaryID:            input.BoundaryID,
			NodeType:              input.NodeType,
			Name:                  input.Name,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk assessment node", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisNodePayload{
		RiskAnalysisNodeEdge: &types.RiskAnalysisNodeConnectionEdge{
			Cursor: node.CursorKey(coredata.RiskAnalysisNodeOrderFieldCreatedAt),
			Node:   types.NewRiskAnalysisNode(node),
		},
	}, nil
}

// UpdateRiskAnalysisNode is the resolver for the updateRiskAnalysisNode field.
func (r *mutationResolver) UpdateRiskAnalysisNode(ctx context.Context, input types.UpdateRiskAnalysisNodeInput) (*types.UpdateRiskAnalysisNodePayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisNodeUpdate)
	if err != nil {
		return nil, err
	}

	node, err := r.riskManagement.UpdateNode(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisNodeRequest{
			ID:         input.ID,
			BoundaryID: gqlutils.UnwrapOmittable(input.BoundaryID),
			NodeType:   input.NodeType,
			Name:       input.Name,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk assessment node", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisNodePayload{RiskAnalysisNode: types.NewRiskAnalysisNode(node)}, nil
}

// DeleteRiskAnalysisNode is the resolver for the deleteRiskAnalysisNode field.
func (r *mutationResolver) DeleteRiskAnalysisNode(ctx context.Context, input types.DeleteRiskAnalysisNodeInput) (*types.DeleteRiskAnalysisNodePayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisNodeID, riskmanagement.ActionRiskAnalysisNodeDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteNode(ctx, scope, input.RiskAnalysisNodeID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk assessment node", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisNodePayload{DeletedRiskAnalysisNodeID: input.RiskAnalysisNodeID}, nil
}

// CreateRiskAnalysisBoundary is the resolver for the createRiskAnalysisBoundary field.
func (r *mutationResolver) CreateRiskAnalysisBoundary(ctx context.Context, input types.CreateRiskAnalysisBoundaryInput) (*types.CreateRiskAnalysisBoundaryPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisBoundaryCreate)
	if err != nil {
		return nil, err
	}

	boundary, err := r.riskManagement.CreateBoundary(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisBoundaryRequest{
			RiskAnalysisDiagramID: input.RiskAnalysisDiagramID,
			ParentBoundaryID:      input.ParentBoundaryID,
			Name:                  input.Name,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk assessment boundary", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisBoundaryPayload{
		RiskAnalysisBoundaryEdge: &types.RiskAnalysisBoundaryConnectionEdge{
			Cursor: boundary.CursorKey(coredata.RiskAnalysisBoundaryOrderFieldCreatedAt),
			Node:   types.NewRiskAnalysisBoundary(boundary),
		},
	}, nil
}

// UpdateRiskAnalysisBoundary is the resolver for the updateRiskAnalysisBoundary field.
func (r *mutationResolver) UpdateRiskAnalysisBoundary(ctx context.Context, input types.UpdateRiskAnalysisBoundaryInput) (*types.UpdateRiskAnalysisBoundaryPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisBoundaryUpdate)
	if err != nil {
		return nil, err
	}

	boundary, err := r.riskManagement.UpdateBoundary(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisBoundaryRequest{
			ID:               input.ID,
			ParentBoundaryID: gqlutils.UnwrapOmittable(input.ParentBoundaryID),
			Name:             input.Name,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk assessment boundary", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisBoundaryPayload{RiskAnalysisBoundary: types.NewRiskAnalysisBoundary(boundary)}, nil
}

// DeleteRiskAnalysisBoundary is the resolver for the deleteRiskAnalysisBoundary field.
func (r *mutationResolver) DeleteRiskAnalysisBoundary(ctx context.Context, input types.DeleteRiskAnalysisBoundaryInput) (*types.DeleteRiskAnalysisBoundaryPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisBoundaryID, riskmanagement.ActionRiskAnalysisBoundaryDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteBoundary(ctx, scope, input.RiskAnalysisBoundaryID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk assessment boundary", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisBoundaryPayload{DeletedRiskAnalysisBoundaryID: input.RiskAnalysisBoundaryID}, nil
}

// CreateRiskAnalysisProcess is the resolver for the createRiskAnalysisProcess field.
func (r *mutationResolver) CreateRiskAnalysisProcess(ctx context.Context, input types.CreateRiskAnalysisProcessInput) (*types.CreateRiskAnalysisProcessPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisProcessCreate)
	if err != nil {
		return nil, err
	}

	process, err := r.riskManagement.CreateProcess(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisProcessRequest{
			RiskAnalysisDiagramID: input.RiskAnalysisDiagramID,
			SourceNodeID:          input.SourceNodeID,
			TargetNodeID:          input.TargetNodeID,
			Name:                  input.Name,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk assessment process", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisProcessPayload{
		RiskAnalysisProcessEdge: &types.RiskAnalysisProcessConnectionEdge{
			Cursor: process.CursorKey(coredata.RiskAnalysisProcessOrderFieldCreatedAt),
			Node:   types.NewRiskAnalysisProcess(process),
		},
	}, nil
}

// UpdateRiskAnalysisProcess is the resolver for the updateRiskAnalysisProcess field.
func (r *mutationResolver) UpdateRiskAnalysisProcess(ctx context.Context, input types.UpdateRiskAnalysisProcessInput) (*types.UpdateRiskAnalysisProcessPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisProcessUpdate)
	if err != nil {
		return nil, err
	}

	process, err := r.riskManagement.UpdateProcess(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisProcessRequest{
			ID:           input.ID,
			SourceNodeID: input.SourceNodeID,
			TargetNodeID: input.TargetNodeID,
			Name:         input.Name,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk assessment process", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisProcessPayload{RiskAnalysisProcess: types.NewRiskAnalysisProcess(process)}, nil
}

// DeleteRiskAnalysisProcess is the resolver for the deleteRiskAnalysisProcess field.
func (r *mutationResolver) DeleteRiskAnalysisProcess(ctx context.Context, input types.DeleteRiskAnalysisProcessInput) (*types.DeleteRiskAnalysisProcessPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisProcessID, riskmanagement.ActionRiskAnalysisProcessDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteProcess(ctx, scope, input.RiskAnalysisProcessID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk assessment process", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisProcessPayload{DeletedRiskAnalysisProcessID: input.RiskAnalysisProcessID}, nil
}

// CreateRiskAnalysisThreat is the resolver for the createRiskAnalysisThreat field.
func (r *mutationResolver) CreateRiskAnalysisThreat(ctx context.Context, input types.CreateRiskAnalysisThreatInput) (*types.CreateRiskAnalysisThreatPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisThreatCreate)
	if err != nil {
		return nil, err
	}

	threat, err := r.riskManagement.CreateThreat(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisThreatRequest{
			RiskAnalysisDiagramID: input.RiskAnalysisDiagramID,
			ProcessID:             input.ProcessID,
			Name:                  input.Name,
			Category:              input.Category,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk threat", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisThreatPayload{
		RiskAnalysisThreatEdge: &types.RiskAnalysisThreatConnectionEdge{
			Cursor: threat.CursorKey(coredata.RiskAnalysisThreatOrderFieldCreatedAt),
			Node:   types.NewRiskAnalysisThreat(threat),
		},
	}, nil
}

// UpdateRiskAnalysisThreat is the resolver for the updateRiskAnalysisThreat field.
func (r *mutationResolver) UpdateRiskAnalysisThreat(ctx context.Context, input types.UpdateRiskAnalysisThreatInput) (*types.UpdateRiskAnalysisThreatPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisThreatUpdate)
	if err != nil {
		return nil, err
	}

	threat, err := r.riskManagement.UpdateThreat(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisThreatRequest{
			ID:        input.ID,
			ProcessID: input.ProcessID,
			Name:      input.Name,
			Category:  input.Category,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk threat", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisThreatPayload{RiskAnalysisThreat: types.NewRiskAnalysisThreat(threat)}, nil
}

// DeleteRiskAnalysisThreat is the resolver for the deleteRiskAnalysisThreat field.
func (r *mutationResolver) DeleteRiskAnalysisThreat(ctx context.Context, input types.DeleteRiskAnalysisThreatInput) (*types.DeleteRiskAnalysisThreatPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisThreatID, riskmanagement.ActionRiskAnalysisThreatDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteThreat(ctx, scope, input.RiskAnalysisThreatID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk threat", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisThreatPayload{DeletedRiskAnalysisThreatID: input.RiskAnalysisThreatID}, nil
}

// CreateRiskAnalysisScenario is the resolver for the createRiskAnalysisScenario field.
func (r *mutationResolver) CreateRiskAnalysisScenario(ctx context.Context, input types.CreateRiskAnalysisScenarioInput) (*types.CreateRiskAnalysisScenarioPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisScenarioCreate)
	if err != nil {
		return nil, err
	}

	scenario, err := r.riskManagement.CreateScenario(
		ctx,
		scope,
		riskmanagement.CreateRiskAnalysisScenarioRequest{
			RiskAnalysisDiagramID: input.RiskAnalysisDiagramID,
			Name:                  input.Name,
			Description:           input.Description,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create risk scenario", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRiskAnalysisScenarioPayload{
		RiskAnalysisScenarioEdge: &types.RiskAnalysisScenarioConnectionEdge{
			Cursor: scenario.CursorKey(coredata.RiskAnalysisScenarioOrderFieldCreatedAt),
			Node:   types.NewRiskAnalysisScenario(scenario),
		},
	}, nil
}

// UpdateRiskAnalysisScenario is the resolver for the updateRiskAnalysisScenario field.
func (r *mutationResolver) UpdateRiskAnalysisScenario(ctx context.Context, input types.UpdateRiskAnalysisScenarioInput) (*types.UpdateRiskAnalysisScenarioPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionRiskAnalysisScenarioUpdate)
	if err != nil {
		return nil, err
	}

	scenario, err := r.riskManagement.UpdateScenario(
		ctx,
		scope,
		riskmanagement.UpdateRiskAnalysisScenarioRequest{
			ID:          input.ID,
			Name:        input.Name,
			Description: gqlutils.UnwrapOmittable(input.Description),
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update risk scenario", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateRiskAnalysisScenarioPayload{RiskAnalysisScenario: types.NewRiskAnalysisScenario(scenario)}, nil
}

// DeleteRiskAnalysisScenario is the resolver for the deleteRiskAnalysisScenario field.
func (r *mutationResolver) DeleteRiskAnalysisScenario(ctx context.Context, input types.DeleteRiskAnalysisScenarioInput) (*types.DeleteRiskAnalysisScenarioPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisScenarioID, riskmanagement.ActionRiskAnalysisScenarioDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteScenario(ctx, scope, input.RiskAnalysisScenarioID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete risk scenario", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteRiskAnalysisScenarioPayload{DeletedRiskAnalysisScenarioID: input.RiskAnalysisScenarioID}, nil
}

// LinkRiskAnalysisScenarioThreat is the resolver for the linkRiskAnalysisScenarioThreat field.
func (r *mutationResolver) LinkRiskAnalysisScenarioThreat(ctx context.Context, input types.LinkRiskAnalysisScenarioThreatInput) (*types.LinkRiskAnalysisScenarioThreatPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisScenarioID, riskmanagement.ActionRiskAnalysisScenarioThreatLink)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.LinkScenarioThreat(
		ctx,
		scope,
		riskmanagement.LinkRiskAnalysisScenarioThreatRequest{
			RiskAnalysisScenarioID: input.RiskAnalysisScenarioID,
			ThreatID:               input.ThreatID,
		},
	); err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot link risk scenario threat", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scenario, err := r.riskManagement.GetScenario(ctx, scope, input.RiskAnalysisScenarioID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load risk scenario", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.LinkRiskAnalysisScenarioThreatPayload{RiskAnalysisScenario: types.NewRiskAnalysisScenario(scenario)}, nil
}

// UnlinkRiskAnalysisScenarioThreat is the resolver for the unlinkRiskAnalysisScenarioThreat field.
func (r *mutationResolver) UnlinkRiskAnalysisScenarioThreat(ctx context.Context, input types.UnlinkRiskAnalysisScenarioThreatInput) (*types.UnlinkRiskAnalysisScenarioThreatPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisScenarioID, riskmanagement.ActionRiskAnalysisScenarioThreatUnlink)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.UnlinkScenarioThreat(
		ctx,
		scope,
		riskmanagement.UnlinkRiskAnalysisScenarioThreatRequest{
			RiskAnalysisScenarioID: input.RiskAnalysisScenarioID,
			ThreatID:               input.ThreatID,
		},
	); err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot unlink risk scenario threat", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scenario, err := r.riskManagement.GetScenario(ctx, scope, input.RiskAnalysisScenarioID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load risk scenario", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.UnlinkRiskAnalysisScenarioThreatPayload{RiskAnalysisScenario: types.NewRiskAnalysisScenario(scenario)}, nil
}

// LinkRiskAnalysisScenarioRisk is the resolver for the linkRiskAnalysisScenarioRisk field.
func (r *mutationResolver) LinkRiskAnalysisScenarioRisk(ctx context.Context, input types.LinkRiskAnalysisScenarioRiskInput) (*types.LinkRiskAnalysisScenarioRiskPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisScenarioID, riskmanagement.ActionRiskAnalysisScenarioRiskLink)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.LinkScenarioRisk(
		ctx,
		scope,
		riskmanagement.LinkRiskAnalysisScenarioRiskRequest{
			RiskAnalysisScenarioID: input.RiskAnalysisScenarioID,
			RiskID:                 input.RiskID,
		},
	); err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot link risk scenario risk", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scenario, err := r.riskManagement.GetScenario(ctx, scope, input.RiskAnalysisScenarioID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load risk scenario", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	s := types.NewRiskAnalysisScenario(scenario)

	return &types.LinkRiskAnalysisScenarioRiskPayload{
		RiskAnalysisScenario: s,
		RiskAnalysisScenarioEdge: &types.RiskAnalysisScenarioConnectionEdge{
			Cursor: scenario.CursorKey(coredata.RiskAnalysisScenarioOrderFieldCreatedAt),
			Node:   s,
		},
	}, nil
}

// UnlinkRiskAnalysisScenarioRisk is the resolver for the unlinkRiskAnalysisScenarioRisk field.
func (r *mutationResolver) UnlinkRiskAnalysisScenarioRisk(ctx context.Context, input types.UnlinkRiskAnalysisScenarioRiskInput) (*types.UnlinkRiskAnalysisScenarioRiskPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisScenarioID, riskmanagement.ActionRiskAnalysisScenarioRiskUnlink)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.UnlinkScenarioRisk(
		ctx,
		scope,
		riskmanagement.UnlinkRiskAnalysisScenarioRiskRequest{
			RiskAnalysisScenarioID: input.RiskAnalysisScenarioID,
			RiskID:                 input.RiskID,
		},
	); err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot unlink risk scenario risk", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scenario, err := r.riskManagement.GetScenario(ctx, scope, input.RiskAnalysisScenarioID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load risk scenario", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.UnlinkRiskAnalysisScenarioRiskPayload{
		RiskAnalysisScenario:          types.NewRiskAnalysisScenario(scenario),
		DeletedRiskAnalysisScenarioID: input.RiskAnalysisScenarioID,
	}, nil
}

// PublishRiskAnalysis is the resolver for the publishRiskAnalysis field.
func (r *mutationResolver) PublishRiskAnalysis(ctx context.Context, input types.PublishRiskAnalysisInput) (*types.PublishRiskAnalysisPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisID, riskmanagement.ActionRiskAnalysisPublish)
	if err != nil {
		return nil, err
	}

	document, documentVersion, err := r.probo.GeneratedDocuments.PublishRiskAnalysis(ctx, scope, input.RiskAnalysisID, input.ApproverIds, input.Minor)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot publish risk analysis", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.PublishRiskAnalysisPayload{
		DocumentEdge:        types.NewDocumentEdge(document, coredata.DocumentOrderFieldCreatedAt),
		DocumentVersionEdge: types.NewDocumentVersionEdge(documentVersion, coredata.DocumentVersionOrderFieldCreatedAt),
	}, nil
}

// Document is the resolver for the document field.
func (r *riskAnalysisResolver) Document(ctx context.Context, obj *types.RiskAnalysis) (*types.Document, error) {
	if obj.Document == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.Document.ID, probo.ActionDocumentGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	document, err := loaders.Document.Load(ctx, obj.Document.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load document", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewDocument(document), nil
}

// Organization is the resolver for the organization field.
func (r *riskAnalysisResolver) Organization(ctx context.Context, obj *types.RiskAnalysis) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// TreatmentPlans is the resolver for the treatmentPlans field.
func (r *riskAnalysisResolver) TreatmentPlans(ctx context.Context, obj *types.RiskAnalysis, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.TreatmentPlanOrderBy, filter *types.TreatmentPlanFilter, asOf *time.Time) (*types.TreatmentPlanConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionTreatmentPlanList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.TreatmentPlanOrderField]{
		Field:     coredata.TreatmentPlanOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.TreatmentPlanOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	planFilter := coredata.NewTreatmentPlanFilter(nil, nil, nil)
	if filter != nil {
		planFilter = coredata.NewTreatmentPlanFilter(filter.ScoreType, filter.Likelihood, filter.Impact)
	}

	if asOf != nil {
		asOfPage, err := r.riskManagement.ListTreatmentPlansAsOf(
			ctx,
			scope,
			obj.ID,
			*asOf,
			cursor,
			planFilter,
			false,
		)
		if err != nil {
			if errors.Is(err, coredata.ErrResourceNotFound) {
				return nil, gqlutils.NotFound(ctx, err)
			}

			if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
				return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
			}

			r.logger.ErrorCtx(ctx, "cannot list treatment plans as of", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}

		return types.NewTreatmentPlanConnectionAsOf(
			asOfPage.Page,
			r,
			obj.ID,
			planFilter,
			*asOf,
			asOfPage.TotalCount,
			asOfPage.ProgressByID,
		), nil
	}

	p, err := r.riskManagement.ListTreatmentPlansForRiskAnalysisID(ctx, scope, obj.ID, cursor, planFilter)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot list treatment plans", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewTreatmentPlanConnection(p, r, obj.ID, planFilter), nil
}

// MatrixCells is the resolver for the matrixCells field.
func (r *riskAnalysisResolver) MatrixCells(ctx context.Context, obj *types.RiskAnalysis, asOf *time.Time) ([]*coredata.RiskAnalysisMatrixCell, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionTreatmentPlanList)
	if err != nil {
		return nil, err
	}

	counts, err := r.riskManagement.GetRiskAnalysisMatrixCells(ctx, scope, obj.ID, asOf)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get treatment plan matrix cells", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return counts, nil
}

// ScenarioRisks is the resolver for the scenarioRisks field.
func (r *riskAnalysisResolver) ScenarioRisks(ctx context.Context, obj *types.RiskAnalysis, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskOrderBy, filter *types.RiskFilter) (*types.RiskConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionRiskList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskOrderField]{
		Field:     coredata.RiskOrderFieldName,
		Direction: page.OrderDirectionAsc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	riskFilter := coredata.NewRiskFilter(nil)
	if filter != nil {
		riskFilter = coredata.NewRiskFilter(filter.Query)
	}

	p, err := r.riskManagement.ListRisksForRiskAnalysisID(ctx, scope, obj.ID, cursor, riskFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list scenario risks on analysis", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskConnection(p, r, obj.ID, riskFilter), nil
}

// Diagrams is the resolver for the diagrams field.
func (r *riskAnalysisResolver) Diagrams(ctx context.Context, obj *types.RiskAnalysis, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisDiagramOrderBy) (*types.RiskAnalysisDiagramConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisDiagramList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisDiagramOrderField]{
		Field:     coredata.RiskAnalysisDiagramOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisDiagramOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListDiagramsForRiskAnalysisID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk assessment scopes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisDiagramConnection(p, r, obj.ID), nil
}

// Permission is the resolver for the permission field.
func (r *riskAnalysisResolver) Permission(ctx context.Context, obj *types.RiskAnalysis, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisBoundaryConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisBoundaryConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisBoundaryList)
	if err != nil {
		return nil, err
	}

	count, err := r.riskManagement.CountBoundariesForDiagramID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count risk assessment boundaries", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &count, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisList)
	if err != nil {
		return nil, err
	}

	count, err := r.riskManagement.CountForOrganizationID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count risk assessments", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &count, nil
}

// Nodes is the resolver for the nodes field.
func (r *riskAnalysisDiagramResolver) Nodes(ctx context.Context, obj *types.RiskAnalysisDiagram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisNodeOrderBy) (*types.RiskAnalysisNodeConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisNodeList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisNodeOrderField]{
		Field:     coredata.RiskAnalysisNodeOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisNodeOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListNodesForDiagramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk assessment nodes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisNodeConnection(p, r, obj.ID), nil
}

// Boundaries is the resolver for the boundaries field.
func (r *riskAnalysisDiagramResolver) Boundaries(ctx context.Context, obj *types.RiskAnalysisDiagram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisBoundaryOrderBy) (*types.RiskAnalysisBoundaryConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisBoundaryList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisBoundaryOrderField]{
		Field:     coredata.RiskAnalysisBoundaryOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisBoundaryOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListBoundariesForDiagramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk assessment boundaries", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisBoundaryConnection(p, r, obj.ID), nil
}

// Processes is the resolver for the processes field.
func (r *riskAnalysisDiagramResolver) Processes(ctx context.Context, obj *types.RiskAnalysisDiagram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisProcessOrderBy) (*types.RiskAnalysisProcessConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisProcessList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisProcessOrderField]{
		Field:     coredata.RiskAnalysisProcessOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisProcessOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListProcessesForDiagramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk assessment processes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisProcessConnection(p, r, obj.ID), nil
}

// Threats is the resolver for the threats field.
func (r *riskAnalysisDiagramResolver) Threats(ctx context.Context, obj *types.RiskAnalysisDiagram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisThreatOrderBy) (*types.RiskAnalysisThreatConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisThreatList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisThreatOrderField]{
		Field:     coredata.RiskAnalysisThreatOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisThreatOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListThreatsForDiagramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk threats", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisThreatConnection(p, r, obj.ID), nil
}

// Scenarios is the resolver for the scenarios field.
func (r *riskAnalysisDiagramResolver) Scenarios(ctx context.Context, obj *types.RiskAnalysisDiagram, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisScenarioOrderBy) (*types.RiskAnalysisScenarioConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisScenarioList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisScenarioOrderField]{
		Field:     coredata.RiskAnalysisScenarioOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisScenarioOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListScenariosForDiagramID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list risk scenarios", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisScenarioConnection(p, r, obj.ID), nil
}

// MermaidChart is the resolver for the mermaidChart field.
func (r *riskAnalysisDiagramResolver) MermaidChart(ctx context.Context, obj *types.RiskAnalysisDiagram) (string, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisDiagramGet)
	if err != nil {
		return "", err
	}

	chart, err := r.riskManagement.BuildDiagramMermaidChart(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot build risk assessment scope mermaid chart", log.Error(err))
		return "", gqlutils.Internal(ctx)
	}

	return chart, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisDiagramConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisDiagramConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisDiagramList)
	if err != nil {
		return nil, err
	}

	count, err := r.riskManagement.CountDiagramsForRiskAnalysisID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count risk assessment scopes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &count, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisNodeConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisNodeConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisNodeList)
	if err != nil {
		return nil, err
	}

	count, err := r.riskManagement.CountNodesForDiagramID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count risk assessment nodes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &count, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisProcessConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisProcessConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisProcessList)
	if err != nil {
		return nil, err
	}

	count, err := r.riskManagement.CountProcessesForDiagramID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count risk assessment processes", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &count, nil
}

// Diagram is the resolver for the diagram field.
func (r *riskAnalysisScenarioResolver) Diagram(ctx context.Context, obj *types.RiskAnalysisScenario) (*types.RiskAnalysisDiagram, error) {
	scope, err := r.authorize(ctx, obj.RiskAnalysisDiagramID, riskmanagement.ActionRiskAnalysisDiagramGet)
	if err != nil {
		return nil, err
	}

	raDiagram, err := r.riskManagement.GetDiagram(ctx, scope, obj.RiskAnalysisDiagramID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load risk assessment scope", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisDiagram(raDiagram), nil
}

// Threats is the resolver for the threats field.
func (r *riskAnalysisScenarioResolver) Threats(ctx context.Context, obj *types.RiskAnalysisScenario, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskAnalysisThreatOrderBy) (*types.RiskAnalysisThreatConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionRiskAnalysisThreatList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskAnalysisThreatOrderField]{
		Field:     coredata.RiskAnalysisThreatOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskAnalysisThreatOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListThreatsForScenarioID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list scenario threats", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysisThreatConnection(p, r, obj.ID), nil
}

// Risks is the resolver for the risks field.
func (r *riskAnalysisScenarioResolver) Risks(ctx context.Context, obj *types.RiskAnalysisScenario, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskOrderBy) (*types.RiskConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionRiskList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskOrderField]{
		Field:     coredata.RiskOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskOrderField]{Field: orderBy.Field, Direction: orderBy.Direction}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	p, err := r.riskManagement.ListRisksForScenarioID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list scenario risks", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskConnection(p, r, obj.ID, nil), nil
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisScenarioConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisScenarioConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisScenarioList)
	if err != nil {
		return nil, err
	}

	switch obj.Resolver.(type) {
	case *riskAnalysisDiagramResolver:
		count, err := r.riskManagement.CountScenariosForDiagramID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count risk scenarios", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &count, nil
	case *organizationResolver:
		count, err := r.riskManagement.CountScenariosForOrganizationID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count risk scenarios", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &count, nil
	default:
		count, err := r.riskManagement.CountScenariosForRiskID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count risk scenarios", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &count, nil
	}
}

// TotalCount is the resolver for the totalCount field.
func (r *riskAnalysisThreatConnectionResolver) TotalCount(ctx context.Context, obj *types.RiskAnalysisThreatConnection) (*int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionRiskAnalysisThreatList)
	if err != nil {
		return nil, err
	}

	switch obj.Resolver.(type) {
	case *riskAnalysisScenarioResolver:
		count, err := r.riskManagement.CountThreatsForScenarioID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count scenario threats", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &count, nil
	default:
		count, err := r.riskManagement.CountThreatsForDiagramID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count risk threats", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}

		return &count, nil
	}
}

// RiskAnalysis returns schema.RiskAnalysisResolver implementation.
func (r *Resolver) RiskAnalysis() schema.RiskAnalysisResolver { return &riskAnalysisResolver{r} }

// RiskAnalysisBoundaryConnection returns schema.RiskAnalysisBoundaryConnectionResolver implementation.
func (r *Resolver) RiskAnalysisBoundaryConnection() schema.RiskAnalysisBoundaryConnectionResolver {
	return &riskAnalysisBoundaryConnectionResolver{r}
}

// RiskAnalysisConnection returns schema.RiskAnalysisConnectionResolver implementation.
func (r *Resolver) RiskAnalysisConnection() schema.RiskAnalysisConnectionResolver {
	return &riskAnalysisConnectionResolver{r}
}

// RiskAnalysisDiagram returns schema.RiskAnalysisDiagramResolver implementation.
func (r *Resolver) RiskAnalysisDiagram() schema.RiskAnalysisDiagramResolver {
	return &riskAnalysisDiagramResolver{r}
}

// RiskAnalysisDiagramConnection returns schema.RiskAnalysisDiagramConnectionResolver implementation.
func (r *Resolver) RiskAnalysisDiagramConnection() schema.RiskAnalysisDiagramConnectionResolver {
	return &riskAnalysisDiagramConnectionResolver{r}
}

// RiskAnalysisNodeConnection returns schema.RiskAnalysisNodeConnectionResolver implementation.
func (r *Resolver) RiskAnalysisNodeConnection() schema.RiskAnalysisNodeConnectionResolver {
	return &riskAnalysisNodeConnectionResolver{r}
}

// RiskAnalysisProcessConnection returns schema.RiskAnalysisProcessConnectionResolver implementation.
func (r *Resolver) RiskAnalysisProcessConnection() schema.RiskAnalysisProcessConnectionResolver {
	return &riskAnalysisProcessConnectionResolver{r}
}

// RiskAnalysisScenario returns schema.RiskAnalysisScenarioResolver implementation.
func (r *Resolver) RiskAnalysisScenario() schema.RiskAnalysisScenarioResolver {
	return &riskAnalysisScenarioResolver{r}
}

// RiskAnalysisScenarioConnection returns schema.RiskAnalysisScenarioConnectionResolver implementation.
func (r *Resolver) RiskAnalysisScenarioConnection() schema.RiskAnalysisScenarioConnectionResolver {
	return &riskAnalysisScenarioConnectionResolver{r}
}

// RiskAnalysisThreatConnection returns schema.RiskAnalysisThreatConnectionResolver implementation.
func (r *Resolver) RiskAnalysisThreatConnection() schema.RiskAnalysisThreatConnectionResolver {
	return &riskAnalysisThreatConnectionResolver{r}
}

type (
	riskAnalysisResolver                   struct{ *Resolver }
	riskAnalysisBoundaryConnectionResolver struct{ *Resolver }
	riskAnalysisConnectionResolver         struct{ *Resolver }
	riskAnalysisDiagramResolver            struct{ *Resolver }
	riskAnalysisDiagramConnectionResolver  struct{ *Resolver }
	riskAnalysisNodeConnectionResolver     struct{ *Resolver }
	riskAnalysisProcessConnectionResolver  struct{ *Resolver }
	riskAnalysisScenarioResolver           struct{ *Resolver }
	riskAnalysisScenarioConnectionResolver struct{ *Resolver }
	riskAnalysisThreatConnectionResolver   struct{ *Resolver }
)
