package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/probot"
	slackchannel "go.probo.inc/probo/pkg/probot/channel/slack"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// SetSlackbotNotificationChannel is the resolver for the setSlackbotNotificationChannel field.
func (r *mutationResolver) SetSlackbotNotificationChannel(ctx context.Context, input types.SetSlackbotNotificationChannelInput) (*types.SetSlackbotNotificationChannelPayload, error) {
	if r.slackbotInstallations == nil ||
		r.botDeliveryDestinations == nil ||
		r.complianceMessages == nil {
		return nil, gqlutils.NotFound(ctx, slackchannel.ErrSlackbotNotInstalled)
	}

	scope, err := r.authorize(
		ctx,
		input.CompliancePortalID,
		probo.ActionConnectorInitiate,
	)
	if err != nil {
		return nil, err
	}

	compliancePortal, err := r.management.Get(
		ctx,
		scope,
		input.CompliancePortalID,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load compliance portal", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	destination, err := applySlackbotNotificationChannel(
		ctx,
		r.botDeliveryDestinations,
		r.complianceMessages,
		scope,
		compliancePortal.OrganizationID,
		input.CompliancePortalID,
		input.ChannelID,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot set Slackbot notification channel", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.SetSlackbotNotificationChannelPayload{
		Channel: &types.SlackbotNotificationChannel{
			ChannelID:   destination.ExternalDestinationID,
			ChannelName: destination.ExternalName,
		},
	}, nil
}

// ClearSlackbotNotificationChannel is the resolver for the clearSlackbotNotificationChannel field.
func (r *mutationResolver) ClearSlackbotNotificationChannel(ctx context.Context, input types.ClearSlackbotNotificationChannelInput) (*types.ClearSlackbotNotificationChannelPayload, error) {
	if r.slackbotInstallations == nil || r.botDeliveryDestinations == nil {
		return nil, gqlutils.NotFound(ctx, slackchannel.ErrSlackbotNotInstalled)
	}

	scope, err := r.authorize(
		ctx,
		input.CompliancePortalID,
		probo.ActionConnectorInitiate,
	)
	if err != nil {
		return nil, err
	}

	compliancePortal, err := r.management.Get(
		ctx,
		scope,
		input.CompliancePortalID,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load compliance portal", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if err := r.botDeliveryDestinations.ClearDestination(
		ctx,
		scope,
		compliancePortal.OrganizationID,
		probot.DeliveryTarget{
			Namespace: "compliance_portal",
			Key:       input.CompliancePortalID.String(),
		},
	); err != nil {
		r.logger.ErrorCtx(ctx, "cannot clear Slackbot notification channel", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.ClearSlackbotNotificationChannelPayload{
		ChannelID: nil,
	}, nil
}

// UninstallSlackbot is the resolver for the uninstallSlackbot field.
func (r *mutationResolver) UninstallSlackbot(ctx context.Context, input types.UninstallSlackbotInput) (*types.UninstallSlackbotPayload, error) {
	if r.slackbotInstallations == nil {
		return nil, gqlutils.NotFound(ctx, slackchannel.ErrSlackbotNotInstalled)
	}

	scope, err := r.authorize(
		ctx,
		input.OrganizationID,
		probo.ActionConnectorDelete,
	)
	if err != nil {
		return nil, err
	}

	if err := r.slackbotInstallations.Uninstall(
		ctx,
		scope,
		input.OrganizationID,
	); err != nil {
		r.logger.ErrorCtx(ctx, "cannot uninstall Slackbot", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	organization, err := r.probo.Organizations.Get(
		ctx,
		scope,
		input.OrganizationID,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load organization after uninstalling Slackbot", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.UninstallSlackbotPayload{
		Organization: types.NewOrganization(organization),
	}, nil
}
