package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/task"
)

// Actor is the resolver for the actor field.
func (r *taskActivityResolver) Actor(ctx context.Context, obj *types.TaskActivity) (*types.Profile, error) {
	if obj.Actor == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.Actor.ID, iam.ActionMembershipProfileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	actor, err := loaders.Profile.Load(ctx, obj.Actor.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get task activity actor", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(actor), nil
}

// Permission is the resolver for the permission field.
func (r *taskActivityResolver) Permission(ctx context.Context, obj *types.TaskActivity, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *taskActivityConnectionResolver) TotalCount(ctx context.Context, obj *types.TaskActivityConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, task.ActionTaskActivityList)
	if err != nil {
		return 0, err
	}

	count, err := r.task.CountActivitiesForTaskID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count task activities", log.Error(err))

		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// TaskActivity returns schema.TaskActivityResolver implementation.
func (r *Resolver) TaskActivity() schema.TaskActivityResolver { return &taskActivityResolver{r} }

// TaskActivityConnection returns schema.TaskActivityConnectionResolver implementation.
func (r *Resolver) TaskActivityConnection() schema.TaskActivityConnectionResolver {
	return &taskActivityConnectionResolver{r}
}

type (
	taskActivityResolver           struct{ *Resolver }
	taskActivityConnectionResolver struct{ *Resolver }
)
