package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/task"
	"go.probo.inc/probo/pkg/validator"
)

// CreateTaskComment is the resolver for the createTaskComment field.
func (r *mutationResolver) CreateTaskComment(ctx context.Context, input types.CreateTaskCommentInput) (*types.CreateTaskCommentPayload, error) {
	scope, err := r.authorize(ctx, input.TaskID, task.ActionTaskCommentCreate)
	if err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)

	taskComment, err := r.task.CreateComment(
		ctx, scope,
		task.CreateTaskCommentRequest{
			TaskID:     input.TaskID,
			OwnerID:    input.OwnerID,
			IdentityID: identity.ID,
			Content:    input.Content,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create task comment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateTaskCommentPayload{
		TaskCommentEdge: types.NewTaskCommentEdge(taskComment, coredata.TaskCommentOrderFieldCreatedAt),
	}, nil
}

// UpdateTaskComment is the resolver for the updateTaskComment field.
func (r *mutationResolver) UpdateTaskComment(ctx context.Context, input types.UpdateTaskCommentInput) (*types.UpdateTaskCommentPayload, error) {
	scope, err := r.authorize(ctx, input.TaskCommentID, task.ActionTaskCommentUpdate)
	if err != nil {
		return nil, err
	}

	taskComment, err := r.task.UpdateComment(
		ctx, scope,
		task.UpdateTaskCommentRequest{
			ID:      input.TaskCommentID,
			OwnerID: gqlutils.UnwrapOmittable(input.OwnerID),
			Content: gqlutils.UnwrapOmittable(input.Content),
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update task comment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateTaskCommentPayload{
		TaskComment: types.NewTaskComment(taskComment),
	}, nil
}

// DeleteTaskComment is the resolver for the deleteTaskComment field.
func (r *mutationResolver) DeleteTaskComment(ctx context.Context, input types.DeleteTaskCommentInput) (*types.DeleteTaskCommentPayload, error) {
	scope, err := r.authorize(ctx, input.TaskCommentID, task.ActionTaskCommentDelete)
	if err != nil {
		return nil, err
	}

	if err := r.task.DeleteComment(ctx, scope, input.TaskCommentID); err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot delete task comment", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteTaskCommentPayload{
		DeletedTaskCommentID: input.TaskCommentID,
	}, nil
}

// Owner is the resolver for the owner field.
func (r *taskCommentResolver) Owner(ctx context.Context, obj *types.TaskComment) (*types.Profile, error) {
	if obj.Owner == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.Owner.ID, iam.ActionMembershipProfileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	owner, err := loaders.Profile.Load(ctx, obj.Owner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get task comment owner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(owner), nil
}

// Task is the resolver for the task field.
func (r *taskCommentResolver) Task(ctx context.Context, obj *types.TaskComment) (*types.Task, error) {
	if _, err := r.authorize(ctx, obj.Task.ID, task.ActionTaskGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	task, err := loaders.Task.Load(ctx, obj.Task.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get task", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewTask(task), nil
}

// Permission is the resolver for the permission field.
func (r *taskCommentResolver) Permission(ctx context.Context, obj *types.TaskComment, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *taskCommentConnectionResolver) TotalCount(ctx context.Context, obj *types.TaskCommentConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, task.ActionTaskCommentList)
	if err != nil {
		return 0, err
	}

	count, err := r.task.CountCommentsForTaskID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count task comments", log.Error(err))

		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// TaskComment returns schema.TaskCommentResolver implementation.
func (r *Resolver) TaskComment() schema.TaskCommentResolver { return &taskCommentResolver{r} }

// TaskCommentConnection returns schema.TaskCommentConnectionResolver implementation.
func (r *Resolver) TaskCommentConnection() schema.TaskCommentConnectionResolver {
	return &taskCommentConnectionResolver{r}
}

type (
	taskCommentResolver           struct{ *Resolver }
	taskCommentConnectionResolver struct{ *Resolver }
)
